-   id: textlint
    name: textlint
    entry: textlint
    language: node
    'files': \.(md|mdown|markdown)$
    args: []
    require_serial: false
    additional_dependencies: ["textlint@11.9.1"]
    minimum_pre_commit_version: '0'
